### ISSUE TITLE
SMTP problem attachment

### ISSUE THREAD

**Issue by ins0u** [Eden-PHP/Mail#28]
Hi,

I have a problem when I try to send an attachment..

My code : 

```
$nameImage = "file.jpg";
$pathToFile = "../../Data/Image/file.jpg";
$typeMime = mime_content_type($pathToFile);

$smtp = eden('mail')->smtp(_SMTP,_USER_EMAIL,_USER_PASSWORD,465,true);
$smtp->setSubject("Subject")
->setBody($MessageDecode,true)
->addTo($Email)
->addAttachment($nameImage , $pathToFile, $typeMime)        
->send(array("From"=>"Me"));
$smtp->disconnect();
```

When I receive the e-mail, the attachment is invalid :/
An idea ? A solution ?

Thx :)

**Comment by nivanmorgan** [comment]
I'm having the same problem.. @ins0u, @kzap  ... did you find a solution. I'm using laravel so I put

if($request->hasFile('attachments')){

            $attach = $request->file('attachments');

            foreach($attach as $attachment1) {

                $path = $attachment1->store('uploads');
                $file_name  = $attachment1->getClientOriginalName();
                $mime_type  = $attachment1->getClientMimeType();
            }

            $smtp->setSubject($request->input('subject'))
                ->setBody($request->input('content'), true)
                ->addTo($request->input('to'))
                ->addAttachment($file_name, $path, $mime_type)
                ->send();

        }
I get the email with the correct name and extension but nothing renders.. and I get an error unsupported filetype

**Comment by kzap** [comment]
I suggest using an updated mail library like Swiftmail

**Comment by nivanmorgan** [comment]
@kzap I fixed the problems by getting the content of the file stored instead of /path/to/file ... it works fine now.

 if($request->hasFile('attachments')){ $attach = $request->file('attachments');  {
foreach($attach as $attachment1) { 
$file= $attachment1->store('uploads'); 
$file_name = $attachment1->getClientOriginalName(); 
$mime_type = $attachment1->getClientMimeType(); 
} 
$contents = Storage::get($file);


$smtp
->setSubject($request->input('subject'))
 ->setBody($request->input('content'), true) 
->addTo($request->input('to')) 
->addAttachment($file_name, $$contents , $mime_type) ->send();
 }

**Comment by ins0u** [comment]
I come back on this problem a few months later and thank you nivanmorgan for your solution, it works now.

My code:

```
$nameImage = "file.jpg";
$pathToFile = file_get_contents("../../Data/Image/file.jpg"); // Fix here ^^
$typeMime = mime_content_type($pathToFile);

$smtp = eden('mail')->smtp(_SMTP,_USER_EMAIL,_USER_PASSWORD,465,true);
$smtp->setSubject("Subject")
->setBody($MessageDecode,true)
->addTo($Email)
->addAttachment($nameImage , $pathToFile, $typeMime)        
->send(array("From"=>"Me"));
$smtp->disconnect();
```
