### ISSUE TITLE
no way to delete messages

### ISSUE THREAD

**Issue by smartcatdev** [Eden-PHP/Mail#53]
i cant delete messages. i have to switch off this library -
it's too bad because i prefer this over the alternatives.

**Comment by DerDu** [comment]
indeed.. issue #1 was my two cent's but just got closed :/

**Comment by cblanquera** [comment]
Hello @DerDu I just reviewed the case, but no PR was submitted. I think that is a valid solution. Yesterday I spent the extra time reviewing PRs. Submit one and I'll pass it though. I closed the original ticket in order to get organized. and based on #1 there wasn't a call to action to do, so that's why I closed it.

**Comment by DerDu** [comment]
@cblanquera it's fine to be organized 😏 
.. but there "was" a PR https://github.com/Eden-PHP/Mail/pull/2 
😅

**Comment by cblanquera** [comment]
https://github.com/Eden-PHP/Mail/commit/ae34e7ba2c3e4bb116ab2824ffc0b7843d63fb67
